apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode2-deployment
  labels:
    app: episode2
spec:
  replicas: 1 # Adjust the replica count as needed
  selector:
    matchLabels:
      app: episode2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: episode2
    spec:
      containers:
        - name: ep2-frontend
          image: masoodghauri/ep2-frontend:latest
          ports:
            - containerPort: 3002
          imagePullPolicy: Always
        - name: ep2-backend
          image: masoodghauri/ep2-backend:latest
          ports:
            - containerPort: 8002
          imagePullPolicy: Always
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27018
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: episode2-service
spec:
  selector:
    app: episode2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3002
    - name: backend
      protocol: TCP
      port: 8002
      targetPort: 8002
    - name: mongodb
      protocol: TCP
      port: 27018
      targetPort: 27018
  type: ClusterIP
