apiVersion: v1
kind: Pod
metadata:
  name: episode1-pod
spec:
  containers:
    - name: ep1-frontend
      image: masoodghauri/ep1-frontend:latest
      ports:
        - containerPort: 3001
      imagePullPolicy: Always
    - name: ep1-backend
      image: masoodghauri/ep1-backend:latest
      ports:
        - containerPort: 8001
      imagePullPolicy: Always
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      imagePullPolicy: Always
