apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode3-deployment
  labels:
    app: episode3
spec:
  replicas: 1 # Adjust the replica count as needed
  selector:
    matchLabels:
      app: episode3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: episode3
    spec:
      containers:
        - name: ep3-frontend
          image: masoodghauri/ep3-frontend:latest
          ports:
            - containerPort: 3003
          imagePullPolicy: Always
        - name: ep1-backend
          image: masoodghauri/ep3-backend:latest
          ports:
            - containerPort: 8003
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: episode3-service
spec:
  selector:
    app: episode3
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3003
    - name: backend
      protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
