apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode5-deployment
  labels:
    app: episode5
spec:
  replicas: 1 # Adjust the replica count as needed
  selector:
    matchLabels:
      app: episode5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: episode5
    spec:
      containers:
        - name: ep1-frontend
          image: masoodghauri/ep5-frontend:latest
          ports:
            - containerPort: 3005
          imagePullPolicy: Always
        - name: ep1-backend
          image: masoodghauri/ep5-backend:latest
          ports:
            - containerPort: 8005
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: episode5-service
spec:
  selector:
    app: episode5
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3005
    - name: backend
      protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP
