apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode4-deployment
  labels:
    app: episode4
spec:
  replicas: 1 # Adjust the replica count as needed
  selector:
    matchLabels:
      app: episode4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: episode4
    spec:
      containers:
        - name: ep4-frontend
          image: masoodghauri/ep4-frontend:latest
          ports:
            - containerPort: 3004
          imagePullPolicy: Always
        - name: ep1-backend
          image: masoodghauri/ep4-backend:latest
          ports:
            - containerPort: 8004
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: episode4-service
spec:
  selector:
    app: episode4
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3004
    - name: backend
      protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
